import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./styles.css";
import { cn } from "@/lib/utils";
import AppProvider from "@/context/AppProvider";
import AuthProvider from "@/context/AuthProvider";
import ThemeProvider from "@/context/ThemeProvider";
import QueryProvider from "@/context/QueryProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Investify - Sistema de Investimentos",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR" suppressHydrationWarning>
      <body
        className={cn(
          "min-w-screen min-h-screen bg-background font-sans antialiased",
          inter.className,
        )}
      >
        <QueryProvider>
          <AppProvider>
            <ThemeProvider
              attribute="class"
              defaultTheme="dark"
              enableSystem={false}
            >
              <AuthProvider>{children}</AuthProvider>
            </ThemeProvider>
          </AppProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
