import type { Metadata } from "next";
import { Poppins, Geist } from "next/font/google";
import "./styles.css";
import Navbar from "../components/Navbar";
import { cn } from "@/lib/utils";

const geist = Geist({subsets:['latin'],variable:'--font-sans'});

const poppins = Poppins({
  subsets: ["latin"],
  variable: "--font-poppins",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});




export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="pt-BR" className={cn("font-sans", geist.variable)}
    >
      <body className={poppins.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
